### ISSUE TITLE
Add tests for awesome mailto: links

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#16]
# Discussion

This is a not-awesome mailto link:

    <a href="mailto:support@pacificmedicaltraining.com">Email us</a>

This is an awesome link:

    <a href="mailto:support@pacificmedicaltraining.com?subject=Signing up&amp;body=Hello,\nI'd like to sign up for your course, can you please send me more information.">Email us</a>

We should use awesome links as psychological warfare against users. Users will send us emails with stupid or annoying emails that we don't want. So instead we prefill the email with the message we want to receive. It takes active cognitive effort for the user to put in their unwanted message. 

You can make these with a tool like:

> http://www.mailto.co.uk/

*Actually that link does not work with /n, please recommend a better tool.*

*Also see http://stackoverflow.com/a/41365892/300224*

# Work plan

- [x] Create extension for html-proofer that checks for awesome mailto links.
- [x] I will publish it in a new repo.
- [ ] Integrate it into this project.

**Comment by ilyalyo** [comment]
@fulldecent this tool:
http://marcwitteveen.com/mailtogenerator/
can handle new lines.

**Comment by fulldecent** [comment]
Nice, that tool works great.

**Comment by ilyalyo** [comment]
@fulldecent just to clarify, it's not a PR to public html-proofer repository, it's going to be a private extension?

**Comment by fulldecent** [comment]
Yes, this is correct. We will follow the process here https://github.com/gjtorikian/html-proofer#custom-tests

I do not think html-proofer is interested to include that extension in its normal product.

We can do that work here

https://github.com/fulldecent/html-proofer-mailto-awesome

I suppose that you can set it up as a gem project. Then I will publish the gem to ruby gems. Then we will import it to https://github.com/fulldecent/lightning-sites in the `test` script.

**Comment by ilyalyo** [comment]
Added PR with extension: https://github.com/fulldecent/html-proofer-mailto-awesome/pull/1
May be it would be better to make a fork?

**Comment by fulldecent** [comment]
I think the extension can be done more modularly. I have asked for help at https://github.com/gjtorikian/html-proofer/issues/415

**Comment by fulldecent** [comment]
Please use this approach: https://github.com/gjtorikian/html-proofer#custom-tests

**Comment by ilyalyo** [comment]
This is have it's done now.
What do you think if we will make a fork and add all custom futures in it and use in our travis?

**Comment by fulldecent** [comment]
This should not be a fork. Here is the repository for this module:

https://github.com/fulldecent/html-proofer-mailto-awesome

We just want a simple class using the example in https://github.com/gjtorikian/html-proofer#custom-tests

Then I can publish as a gem. Then we can pull this gem from lightning-sites and call that custom class when we call html-proofer using Ruby.

**Comment by ilyalyo** [comment]
I pushed mailto-awesome class and gemspec into https://github.com/fulldecent/html-proofer-mailto-awesome

**Comment by fulldecent** [comment]
This looks good so far. Please update this file I started: https://github.com/fulldecent/html-proofer-mailto-awesome

**Comment by fulldecent** [comment]
OK, the https://github.com/fulldecent/html-proofer-mailto_awesome project is now published to ruby gems at https://rubygems.org/gems/html-proofer-mailto_awesome

Please use this gem from https://github.com/fulldecent/lightning-sites

**Comment by fulldecent** [comment]
Ready to use html-proofer-mailto_awesome from lightning-sites

**Comment by ilyalyo** [comment]
I updated mailto_awesom, so it can be run optionaly: added option check_mailto_awesome
https://github.com/fulldecent/html-proofer-mailto_awesome/pull/8
and added this check to lighting sites:
https://github.com/fulldecent/lightning-sites/pull/17

**Comment by fulldecent** [comment]
Fixed in fa757fe1d225a2629bd46fca1b96e8047fe3975a
