### ISSUE TITLE
Add tests for XML site map

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#17]
# Discussion

https://support.google.com/webmasters/answer/156184?hl=en

> However, in most cases, your site will benefit from having a sitemap, and you'll never be penalized for having one.

# Work plan

- [x] Find existing tool that does this or create html-proofer extension
- [x] I will host the new extension, if necessary, in a new repo
- [x] Integrate it into this project

**Comment by ilyalyo** [comment]
You want this tool to test that all links in sitemap.xml is valid?

**Comment by fulldecent** [comment]
No. I just want to check that it is a valid XML file. Or if we can validate against an XML schema that is fine too. I just want something simple.

Please do not create a tool until we get a response from https://github.com/gjtorikian/html-proofer/issues/415

**Comment by ilyalyo** [comment]
Got you.

**Comment by fulldecent** [comment]
Here is the new repository:

https://github.com/fulldecent/html-proofer-xml_sitemap

**Comment by ilyalyo** [comment]
Maybe it's better to add this functionality not as htmlproofer extension but as lightning-sites task?
In lightning sites we have @build_dir variable, so I can check sitemap.xml exists and valid. When we run htmlprofer we don't know is directory project root or it's subdirictory.

**Comment by fulldecent** [comment]
Yes, that will work. I will kill the above repository.

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/lightning-sites/pull/16

**Comment by fulldecent** [comment]
PR merged and new version of lightning-sites released. We are ready to update the gemspec here.

**Comment by ilyalyo** [comment]
Added PR with updated Gemfile.lock:
#21

**Comment by fulldecent** [comment]
Beautiful, looks good!
