### ISSUE TITLE
Always have separate source and build

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/html-website-template#7]
## Why

Why not just deploy from the source folder directly to the production web server, especially if no "building" is necessary?

Because there is **always** a build step, even if the build step is just to copy files from the `source` folder to the `build` folder.

## Work plan

 - [x] Create a build task: `rsync:copy_build`
    - [x] Copy from `source` to `build`
 - [x] Create a build task or reusable function `git:check_if_working_copy`
    - [x] Detect if this folder is checked into git
 - [x] Create a build task: `git:save_version`
    - [x] If this folder is checked into git then save the current commit version to `build/VERSION`
    - [x] If there are local changes (dirty) then add an additional `+local-changes` to the `VERSION`
 - [x] Create a build task: `build`
    - [x] By default, this will call `rsync:copy_build` and `git:save_version`, but end users may update it on their own
